services:
  web:
    build: .
    container_name: django-lab-vps-web
    command: uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "8100:8000"
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build: .
    container_name: django-lab-vps-worker
    command: python worker.py
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16-alpine
    container_name: django-lab-vps-postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: django-lab-vps-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
